### ISSUE TITLE
Need binaries for those who can't build

### ISSUE THREAD

**Issue by JMarkMurphy** [WorksOfBarry/IBMiCmd#11]
I am behind a rather aggressive corporate firewall, and do not have VS to build this source. I also don't have the ability to download and install even the community version. It would be nice if there were pre-built binaries available so I can try this out.

**Comment by WorksOfBarry** [comment]
Hi @JMarkMurphy - thank god I already do this!

Check out the Releases tab for the latest `dll` binaries. As a shortcut, here's the latest release: https://github.com/WorksOfBarry/IBMiCmd/releases/tag/1.2.1

**Comment by JMarkMurphy** [comment]
Can you zip it up? My firewall apparently blocks downloads of dll files.

**Comment by WorksOfBarry** [comment]
@JMarkMurphy Here is a zip of version 1.3 for you.

https://www.dropbox.com/s/crrtxstshe7rh4b/IBMiCmd.ZIP?dl=0

**Comment by WorksOfBarry** [comment]
@JMarkMurphy 

While 1.3.1 [is now available](https://github.com/WorksOfBarry/IBMiCmd/releases/tag/1.3.1), can we close this issue?
