### ISSUE TITLE
Plugins not compatible with Unicode Notepad++

### ISSUE THREAD

**Issue by starbuck5250** [WorksOfBarry/IBMiCmd#18]
When starting NP++ I'm seeing popup boxes with text like

'This ANSI plugin is not compatible with your Unicode Notepad++'

Mono.Cecil.dll
NppPluginDllExport.dll
NppPluginDllExportMSBuild.dll

Notepad++ 7.3.3 32-bit

**Comment by WorksOfLiam** [comment]
Hi @starbuck5250 - long time, no talk!

I have just updated to 7.3.3 32-bit and it seems to be working fine for me.

Are you doing a manual build of the plugin?

**Comment by starbuck5250** [comment]
On 16 June 2017 at 05:05, Liam Allan <notifications@github.com> wrote:

> Hi @starbuck5250 - long time, no talk!

Life, my friend.

> I have just updated to 7.3.3 32-bit and it seems to be working fine for me.
>
> Are you doing a manual build of the plugin?

Sorry for the incomplete report.  I ought to know better. :-(
To install, I downloaded the .zip file, extracted all, then used File
Explorer to drill down to DllExport.  Copied the 3 .dll files to the
NPP plugins directory and started NPP.  That's when I got the message
boxes.  I tried it at home on my 64-bit Windows 10 machine and got the
same messages.  I did that because I couldn't readily locate any
installation instructions.

In the course of typing this up I went through many (all?) of the
links in the wiki, trying to locate install instructions, and that's
when I discovered (under Releases) there's a reasonably-named .dll
waiting for me to install.  Co I downloaded IBMiCmd.dll, copied /that/
into the plugins directory, started NPP and all is right in the world.

Apologies for the false alarm, but at least I now know how to report
an issue! :-)

Please close this out; perhaps after writing the installation
instruction section of the wiki.
  --buck

**Comment by WorksOfLiam** [comment]
Hi @starbuck5250!

Glad you got it working. I will work on improving the wiki.

Cheers,
Liam

**Comment by WorksOfLiam** [comment]
Wiki has now been updated. Wiki->Instsllation
