### ISSUE TITLE
Problems with library names containing dots

### ISSUE THREAD

**Issue by f-lombardo** [WorksOfBarry/IBMiCmd#20]
I think there is an issue regarding library names containing dots (e.g. P21.ADDE): they can't be added to library list and in source member listing.

Thanks a lot.

Franco

**Comment by WorksOfLiam** [comment]
Hi

Thanks for opening this @f-lombardo. We will let you know when we push a fix.

For reference, the regex for checking the library name is valid is [here](https://github.com/WorksOfBarry/IBMiCmd/blob/master/IBMiTools/IBMiUtilities.cs#L21).

Cheers,
Liam

**Comment by WorksOfLiam** [comment]
A fix was made in commit 42a8fbbdfc4ed6697535d263879d412e64fe83ea and release 1.5.5 was made which contains this fix and a few other fixes too.

https://github.com/WorksOfBarry/IBMiCmd/releases/tag/1.5.5

@f-lombardo please close this if the fix is working for you 😄

**Comment by f-lombardo** [comment]
The fix works for the library list, anyway it's impossible to edit a member in libraries with dots in their name.
In this example, I'm trying to edit the member APYTRGCL in library P21.XILE, file QCLSRC.
![cattura](https://user-images.githubusercontent.com/280709/28268202-a40b4730-6afd-11e7-864f-02d263fad2a8.PNG)

**Comment by WorksOfLiam** [comment]
I know the issue already but I am away from my desk. Will fix when I am back at my desk :)

**Comment by WorksOfLiam** [comment]
@f-lombardo

A fix has been made (a350f2a93489a4f2e41b9c6a5722b71db5d2dee0) but won't appear officially until next release.

Attached is a preview dll of IBMiCmd 1.5.6.

Let me know how you get on.
[IBMiCmd.zip](https://github.com/WorksOfBarry/IBMiCmd/files/1153222/IBMiCmd.zip)

**Comment by f-lombardo** [comment]
OK, it works now: thank you!
