### ISSUE TITLE
IBMiCmd not compatible with current version of Nodepad++

### ISSUE THREAD

**Issue by WPH-Erhard** [WorksOfBarry/IBMiCmd#35]
I run my Client with WIN7-SP1 / 64 Bit + .NET Framework 4.7.
Starting Notepad++  Version 7.5.1 i get a error message Window 
"IBMiCmd.dll not compatible with the current version of Notepad++"

Which versions of Notepad and IBMCmd i have to take???

Greetings, Thomas

![ibmicmd](https://user-images.githubusercontent.com/32174583/30715012-2edf9dc0-9f15-11e7-8397-c2ee5aa17eb4.JPG)

**Comment by WPH-Erhard** [comment]
Problem ist solved. 
I uninstall my 64-Bit-Version of Notepad++ and install the 32-Bit Version. 
Now all works fine.

**Comment by WorksOfLiam** [comment]
Hi @WPH-Erhard - sorry for not getting back to you. 

Currently we are only shipping 32bit binaries. Of course you're more than welcome to clone and build a 64bit binary.

Cheers
